### ISSUE TITLE
Change the VM parameters

### ISSUE THREAD

**Issue by RamuRChenchaiah** [rajasoun/multipass-dev-box#24]
Steps to change the VM parameters will be helpful

**Comment by rajasoun** [comment]
ReadMe.md to be updated regarding the overriding file for instance.env. Currently,  dev.instance.env is supported. 
Marking as Documentation update Feature Request

**Comment by rajasoun** [comment]
Doc update - Refet https://github.com/rajasoun/multipass-dev-box/tree/develop#vm-configuration--overriding-options
