### ISSUE TITLE
[Windows 10] With current master, error while executing "ci/check_bats.bash -f .precondition"

### ISSUE THREAD

**Issue by RamuRChenchaiah** [rajasoun/multipass-dev-box#27]
**Describe the bug**
>> ci/check_bats.bash -f .precondition

The above attempt for execution does not find the required script file in current master branch. 
**To Reproduce**
1. Checkout master branch
2. Follow the Readme.md file for setup details
3. Scroll down to "Getting Started"
4. Execute "ci/check_bats.bash -f .precondition"
5. It will stop & throw error : 
```
bash: ci/check_bats.bash: No such file or directory
```

**Expected behavior**
May be once the code is in master this error should disappear, but steps to avoid such error in Readme.md will be helpful

**Screenshots**
Not supplied

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
- N/A

**Additional context**
- We executed : git submodule update --init --recursive --remote
- and then started with "ci/check_bats.bash -f .precondition", it worked fine

**Comment by rajasoun** [comment]
Thanks for raising the issue with details. 
ci is a git submodule to this mono repository. The sequence in the ReadMe.md has to be changed.

$ git submodule update --init --recursive --remote 
and then followed by 
$ ci/check_bats.bash precondition 

Will update in develop branch and later merge it to master

**Comment by rajasoun** [comment]
Fixed and Available in Master
