### ISSUE TITLE
[Windows 10] Execution of "export MODE=help && ./multipass.bash" from "Help (Flow) Based - Beginners" failed

### ISSUE THREAD

**Issue by RamuRChenchaiah** [rajasoun/multipass-dev-box#28]
**Describe the bug**
Execution of "export MODE=help && ./multipass.bash" from "Help (Flow) Based - Beginners" failed with error.

**To Reproduce**
1. Go to 'Help (Flow) Based - Beginners' in https://github.com/rajasoun/multipass-dev-box 
2. Execute 'export MODE=help && ./multipass.bash'
3. Select choice 1
4. See error:
```
id_rsa_microcloud & id_rsa_microcloud.pub keys generated successfully
config/microcloud-cloud-init.yaml Generated for microcloud
launch failed: The following errors occurred:
microcloud: timed out waiting for response
```
5. We tried this multiple times in new browser, same result. 

**Expected behavior**
Complete provisioning 

**Screenshots**
- N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
- Also checked the internet connection: Download speed was 37.8Mbps
- Not in Cisco VPN

**Comment by RamuRChenchaiah** [comment]
We see similar issues at:
https://github.com/canonical/multipass/issues/990
https://github.com/canonical/multipass/issues/706
Just thought of sharing.

**Comment by rajasoun** [comment]
@Ramu : Adding debug log code  - will let you know once done

**Comment by rajasoun** [comment]
Based on reading from the issue list -it looks like the Default Switch of the Hyper-V might have issues in providing the IP. Disabling and Enabling seems to work from forums - yet to check
